-- ユーザ
DROP TABLE USER;
CREATE TABLE IF NOT EXISTS USER ( ID VARCHAR(20) NOT NULL, NAME VARCHAR(20) NOT NULL , AUTHORITY INT NOT NULL);
-- パスワード
DROP TABLE PASSWORD;
CREATE TABLE IF NOT EXISTS PASSWORD ( USER_ID VARCHAR(20) NOT NULL,PASSWORD VARCHAR(20) NOT NULL );
-- 結果
DROP TABLE RESULT;
CREATE TABLE IF NOT EXISTS RESULT ( ID INT NOT NULL AUTO_INCREMENT, PARENT_ID INT, USER_ID VARCHAR(20) NOT NULL, BOARD_GAME_ID INT, BOARD_GAME_TITLE VARCHAR(20), PLACE_ID INT, PLACE_NAME VARCHAR(20), SCORE VARCHAR(20), COMMENT VARCHAR(20), CREATE TIMESTAMP NOT NULL);
-- ボードゲーム
DROP TABLE BOARD_GAME;
CREATE TABLE IF NOT EXISTS BOARD_GAME(ID INT NOT NULL AUTO_INCREMENT,  TITLE VARCHAR(20) NOT NULL, PLAYER INT NOT NULL, OVERVIEW VARCHAR(50));
-- 場所
DROP TABLE PLACE;
CREATE TABLE IF NOT EXISTS PLACE (ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(20), URL VARCHAR(50));
-- チェックイン
DROP TABLE CHECK_IN;
CREATE TABLE IF NOT EXISTS CHECK_IN(ID INT NOT NULL AUTO_INCREMENT, USER_ID VARCHAR(20) NOT NULL, PLACE_ID INT NOT NULL, TIMESTAMP TIMESTAMP NOT NULL, CHECKED_OUT BOOLEAN);

INSERT INTO USER (ID, NAME, AUTHORITY) VALUES ('admin', 'あどみん', 0);
INSERT INTO USER (ID, NAME, AUTHORITY) VALUES ('admin1', 'あどみん1', 0);
INSERT INTO USER (ID, NAME, AUTHORITY) VALUES ('admin2', 'あどみん2', 0);
INSERT INTO USER (ID, NAME, AUTHORITY) VALUES ('user', 'ユーザ', 0);
INSERT INTO USER (ID, NAME, AUTHORITY) VALUES ('user1', 'ユーザ1', 0);
INSERT INTO USER (ID, NAME, AUTHORITY) VALUES ('user2', 'ユーザ2', 0);
INSERT INTO PASSWORD (USER_ID, PASSWORD) VALUES ('admin', 'password');
INSERT INTO PASSWORD (USER_ID, PASSWORD) VALUES ('admin1', 'password');
INSERT INTO PASSWORD (USER_ID, PASSWORD) VALUES ('admin2', 'password');
INSERT INTO PASSWORD (USER_ID, PASSWORD) VALUES ('user', 'password');
INSERT INTO PASSWORD (USER_ID, PASSWORD) VALUES ('user1', 'password');
INSERT INTO PASSWORD (USER_ID, PASSWORD) VALUES ('user2', 'password');
INSERT INTO RESULT (ID, PARENT_ID, USER_ID, BOARD_GAME_ID, BOARD_GAME_TITLE, PLACE_ID, PLACE_NAME, SCORE, COMMENT, CREATE) VALUES (0, -1, 'admin', 0, 'ボードゲーム0', 0, 'ボドゲショップ1', 'スコア50', '', parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'));
INSERT INTO BOARD_GAME (ID, TITLE, PLAYER, OVERVIEW) VALUES (0, 'ボードゲーム0', 2, '概要0');
INSERT INTO BOARD_GAME (ID, TITLE, PLAYER, OVERVIEW) VALUES (1, 'ボードゲーム1', 3, '概要1');
INSERT INTO BOARD_GAME (ID, TITLE, PLAYER, OVERVIEW) VALUES (2, 'ボードゲーム2', 4, '概要2');
INSERT INTO PLACE (ID, NAME) VALUES (0, 'ボドゲショップ1');
INSERT INTO PLACE (ID, NAME) VALUES (1, 'ボドゲショップ2');
INSERT INTO PLACE (ID, NAME) VALUES (2, '誰かの家');